azooKey/AzooKeyKanaKanjiConverter

Sources/KanaKanjiConverterModule/TemplateData.swift

Swift5.9以降はExistentialAnyにおかわりが発生するので対応した

[fix] Swift5.9以降のExistentialAny対応

---

Sources/KanaKanjiConverterModule/Converter/Converter.swift

「予測変換が多すぎる」「誤り訂正が強すぎる」という問題が指摘されていたため、次のように変更
1. 予測変換は上位5件のうち最大3件に減らす（今までは4件だった）
2. 誤り訂正を含まない完全一致変換を上位3件までに1つ含める（今までは5件目のあとだった）

[Improve] Improve candidate generation algorithm

---

Sources/KanaKanjiConverterModule/Candidate.swift
Sources/KanaKanjiConverterModule/TemplateData.swift
Sources/SwiftUtils/StringUtils.swift
Tests/KanaKanjiConverterModuleTests/ConverterTests/CandidateTests.swift
Tests/KanaKanjiConverterModuleTests/ConverterTests/ConvesionTests.swift
Tests/KanaKanjiConverterModuleTests/ConverterTests/UnicodeConversionTests.swift

fix https://github.com/ensan-hcl/azooKey/issues/261
TemplateDataをパースするとき、エスケープした文字列の復元が過剰に行われているため、ユーザが入力した「\n」が本当に改行に変更されてしまう不具合があった。これを修正。

[fix] template parse logic

---

.github/workflows/swift.yml
Package.swift

https://github.com/ensan-hcl/azooKey/issues/281 の一環。
* CIを更新
* PackageのSwiftバージョンを更新
* upcoming-feature-flagを追加

[Refactoring] Swiftバージョンを5.9に更新

---

Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift

UniqueにするためにfirstIndexで何度もStringの比較を行っていたので、Dictionaryを使って比較を減らした。これによって全体の3%程度の処理時間が不要になる。

[Performance] 変換結果をUniqueする処理を高速化

---

Sources/KanaKanjiConverterModule/LOUDS/LOUDS.swift

二重のArrayで持っていた部分をflattenしたデータにすることで、構築時の時間コストを抑えた。2%程度速度改善が得られる

[Performance] LOUDSのinit処理を高速化

---

Tests/KanaKanjiConverterModuleTests/ConverterTests/CandidateTests.swift
Tests/KanaKanjiConverterModuleTests/ConverterTests/ConvesionTests.swift
Tests/KanaKanjiConverterModuleTests/ConverterTests/EmailAddressConversionTests.swift
Tests/KanaKanjiConverterModuleTests/ConverterTests/UnicodeConversionTests.swift
Tests/KanaKanjiConverterModuleTests/ConverterTests/WarekiConversionTests.swift

Linux上でテストが成功しないため、より一般的なasyncなtestケースに乗り換えることで成功するようになる。

[Test] @MainActorのテストケースクラスをasyncなtestケースに変更

---

.github/workflows/swift.yml
.gitmodules
Package.swift
Sources/KanaKanjiConverterModuleWithDefaultDictionary/KanaKanjiConverterModuleWithDefaultDictionary.swift
Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ConverterTests/ConverterTests.swift
Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/DicdataStoreTests/DicdataStoreTests.swift

Resolve #3 
[azooKey_dictionary_storage](https://github.com/ensan-hcl/azooKey_dictionary_storage)の導入でサブモジュールとして辞書をgit管理に含められるようになった。
そこで、SwiftPM側で2つのライブラリを提供する。
* 1つは今まで通りの`KanaKanjiConverterModule`
* もう1つは新たに追加する`KanaKanjiConverterModuleWithDefaultDictionary`で、これを用いるとデフォルト辞書データを参照することができる。ただしこちらは25MB程度のバンドルが付いてくる
さらに、これに基づいて変換テストをazooKey側から移植した。これにより、変換テストをより広く行うことができる。

[Feature] デフォルト辞書を提供するモジュールを追加

---

Sources/KanaKanjiConverterModule/DicdataStore/DicdataStore.swift

これまで、長さが1の単語に対しては特別な辞書ファイルを利用していた。
しかし、当初と異なり、現在は検索のdepthを制限する引数があるため、適切に調整すれば候補はそこまで増えない。
そこで、辞書検索において文字数が1の場合の例外的取り扱いを廃止した。
これにより、`p_`辞書が一部削除できるようになる。

[Feature] 予測変換用の辞書検索を単純化

---

Sources/KanaKanjiConverterModule/Converter/CalendarCandidate.swift

This pull request refactors the code in CalendarCandidate.swift to improve the dropping of the "ネン" string. The previous implementation used the `suffix` method, but it has been replaced with the `hasSuffix` method for better readability and performance.

Refactor dropping "ネン" from string in CalendarCandidate.swift

---

.github/workflows/swift.yml

This pull request adds CI support for Swift 5.10. It ensures that Swift 5.9 will be supported as long as the CI passes, and will be stopped if it fails. Fixes #66.

[Tools] Swift 5.10のCIを追加する

---

.devcontainer/devcontainer.json

This pull request updates the Swift image version in the devcontainer.json file to 5.10. It also includes other necessary changes and updates related to the Swift 5.10 version. This resolves issue #68.

Update Swift image version to 5.10

---

Sources/KanaKanjiConverterModule/DicdataStore/LearningMemory.swift

temporary memoryを更新する際、dicdataelementのvalueを更新し忘れていた
https://discord.com/channels/1166734354492440638/1231613018819788881/1231613063820480592

fix: temporary memoryの更新ロジックのバグを修正

---

Sources/KanaKanjiConverterModule/DicdataStore/LearningMemory.swift
Sources/KanaKanjiConverterModule/LOUDS/extension LOUDS.swift

Fix https://github.com/ensan-hcl/azooKey/issues/461
https://github.com/ensan-hcl/azooKey/issues/461 で報告したとおり、学習データの更新ロジックに深刻な不具合があることがわかった。本PRはこれを修正する。
修正前後のデータ形式は互換性を持たないため、マイグレーションが必要となる。この実装は次のように考えて実装する。
修正前に`MetadataElement(lastUsedDay: 42, lastUpdateDay: 42, count: 1...7)`を保存する場合、以下のような形で保存される。これは5バイト7個分と想定して35バイトのデータとなっている。ここから修正前のコードで読み出しを行うと、35バイト中30バイト分（5データ）を有効なデータとして読み出せて、差し引き2個が捨てられる。
```
[0] = 42
[1] = 0
[2] = 42
[3] = 0
[4] = 1
[5] = 0
[6] = 42
[7] = 0
[8] = 42
[9] = 0
[10] = 2
[11] = 0
[12] = 42
[13] = 0
[14] = 42
[15] = 0
[16] = 3
[17] = 0
[18] = 42
[19] = 0
[20] = 42
[21] = 0
[22] = 4
[23] = 0
[24] = 42
[25] = 0
[26] = 42
[27] = 0
[28] = 5
[29] = 0
[30] = 42
[31] = 0
[32] = 42
[33] = 0
[34] = 6
```
修正後のコードでこのデータを読み出そうとした場合、5バイトずつ読み出す。このため、最初の5バイトはそのまま解釈可能だが、残りは解釈が変わる。具体的に …

[Fix] 学習データの更新ロジックを修正

---

Sources/CliTool/Subcommands/RunCommand.swift
Sources/KanaKanjiConverterModule/Converter/ConvertRequestOptions.swift
Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift

```
% anco しかくとさんかく -n 5 --only_whole_conversion --report_score
資格と三角 score: -35.1128
四角と三角 score: -35.4663
視覚と三角 score: -35.8107
資格と参画 score: -36.4517
死角と三角 score: -37.2333
Entropy: 1.6687454757348383
```

[cli] 完全一致変換のみを出力するモードを追加

---

README.md
Sources/CliTool/Subcommands/DictCommands/ReadCommand.swift
Sources/CliTool/Subcommands/RunCommand.swift
Sources/KanaKanjiConverterModule/Converter/ConvertRequestOptions.swift
Sources/KanaKanjiConverterModule/Converter/VersionCandidate.swift
Sources/KanaKanjiConverterModuleWithDefaultDictionary/KanaKanjiConverterModuleWithDefaultDictionary.swift
Tests/KanaKanjiConverterModuleTests/ConverterTests/ConvesionTests.swift
Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ConverterTests/ConverterTests.swift
Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/DicdataStoreTests/DicdataStoreTests.swift
Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/InputGraph/LookupGraphTests.swift
Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/extension Kana2Kanji+InputGraph.swift

`ConvertRequestOptions.Metadata`はこれまで何を指定しても「azooKey」が表示されていたが、サードパーティ製アプリケーションでは望ましい挙動ではなかった。そこで新たなAPIを追加した。また、単純に`nil`を指定することもできるようにした。

[Feature] MetadataのAPIをより柔軟にし、任意のアプリ名を指定可能にした

---

Sources/KanaKanjiConverterModule/Kana2Kanji/all_with_prefix_constraint.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/zenzai.swift
Sources/KanaKanjiConverterModule/Zenz/ZenzContext.swift
Sources/SwiftUtils/ArrayUtils.swift

* 書記素クラスタではなく、コードポイント単位で判定が行われるようにした
* EOSを考慮するようにした

[Fix] 制約の適用を調整した

---

Sources/CliTool/Subcommands/SessionCommand.swift
Sources/KanaKanjiConverterModule/DicdataStore/DicdataElement.swift
Sources/KanaKanjiConverterModule/DicdataStore/DicdataStore.swift
Sources/KanaKanjiConverterModule/Zenz/Zenz.swift
Sources/KanaKanjiConverterModule/Zenz/ZenzContext.swift

Resolve #107 
- Zenzaiに入る前に十分にチェックできている可能性があるので、一旦気にしないことにしてみる。

feat: Zenzaiで学習機能を有効化する

---

Sources/KanaKanjiConverterModule/Kana2Kanji/all_with_prefix_constraint.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/zenzai.swift

計算量の削減のため、通常の変換ではコストが高すぎる候補を初めから除外していた。しかし、Zenzaiの制約付き変換においてはこれによって制約を満たす候補が作れなくなるケースが存在した。
例えば「村に鉄道を引いて『我田引鉄』する議員」という文章では、「我田引鉄」が辞書登録外であるため、「引」「鉄」を組み合わせる必要がある。しかし、「引」単体はコストが高いため、変換から除外される。これによって制約を満たす候補が作れなくなってしまう。
そこでこのPRでは制約付き変換において上記の除外処理を削除した。制約付き変換はそもそも接頭辞制約によって候補が強く絞り込まれるため、変換候補をわざわざ削減しなくても、高速に処理できる。

feat: Zenzaiの制約付き変換において計算から除外する候補を減らした

---

Sources/CliTool/Subcommands/SessionCommand.swift
Sources/KanaKanjiConverterModule/Converter/ConvertRequestOptions.swift
Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/zenzai.swift
Sources/KanaKanjiConverterModule/Zenz/Zenz.swift
Sources/KanaKanjiConverterModule/Zenz/ZenzContext.swift

現状、ZenzaiではN-Best計算が不十分であり、基本的に最善と考えられる候補が1番上に示され、残りはその生成中に作られた候補のみになる。これは多くの場合で十分である一方、「変換してください」vs「返還してください」のような難しいケースで間違えた場合のフラストレーションを溜める原因になっている。
そこでこのPRではN-Best解の計算ロジックを変更した。具体的には、モデルがあまり自信のない変換をしている部分を特定し、そこを迷っている別の文字に切り替えた場合に得られる変換候補をN-Bestに挿入するようにした。

feat: Zenzaiの利用時によりリッチなN-Best解の計算を可能にする

---

Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift

現在、firstClauseResultsとして得られる結果は長さではなくvalueでソートされているが、これでは有用な候補が得られない。そこでまずcorrespondingCountでソートし、その中でvalueでソートするように実装を修正した。

fix: firstClauseResultsとして得られる結果が長さではなくvalueでソートされる挙動を変更

---

.github/workflows/swift.yml
Docs/about_windows_support.md
Package.swift
Sources/llama.cpp/ggml-alloc.h
Sources/llama.cpp/ggml-backend.h
Sources/llama.cpp/ggml.h
Sources/llama.cpp/llama.h
Sources/llama.cpp/module.modulemap

llama.cppをcuda用にビルドしようとしても、clangがうまく対応できていないためにうまく動かない。
cudaを使用するために、
- `llama.cpp/*.h`とビルド済みの`llama.lib`ファイルを用いてswiftをビルド
- 実行時にはdllを参照する
とするように変更した。
CIの変更もしているが、CIではGPUを使うことができないため、CPU用のllamaをビルドしている。

Windowsではllama.cppを分離する

---

Sources/KanaKanjiConverterModule/Kana2Kanji/zenzai.swift

fix: retryの候補として不適切そうな単語を無視する処理を追加

---

Sources/KanaKanjiConverterModule/DicdataStore/DicdataStore.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/all.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/all_with_prefix_constraint.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/zenzai.swift

ZenzaiはDesktopでの利用を想定しているが、typo correctionが行われると不可思議な挙動に見える。そこでこの挙動を削除した

feat: Zenzaiの利用時にtypo correctionを無効化

---

Sources/KanaKanjiConverterModule/DicdataStore/DicdataStore.swift

fix: typo correctionの無効化に関して、条件分岐を逆に指定したミスを修正

---

Sources/CliTool/Subcommands/EvaluateCommand.swift
Sources/KanaKanjiConverterModule/DicdataStore/DicdataElement.swift
Sources/KanaKanjiConverterModule/DicdataStore/DicdataStore.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/all_with_prefix_constraint.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/mid_composition_prediction.swift
Sources/KanaKanjiConverterModule/Zenz/ZenzContext.swift

* `DicdataElement`にユーザ辞書の属性を追加
* 左文脈としてユーザ辞書情報を追加する機能を実装
* `evaluate`コマンドの実装を変更し、jsonファイルを受け取るように変更。また、ユーザ辞書を加味した評価を可能に。

feat: Zenzaiでユーザ辞書を有効化

---

Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift
Sources/KanaKanjiConverterModule/DicdataStore/DicdataStore.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/added_last_1_character.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/added_last_n_character.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/all.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/changed_last_n_character.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/completed_first.swift
Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/DicdataStoreTests/DicdataStoreTests.swift

* macOSでは誤り訂正を完全に無効化することでZenzai利用時と同一のパスに入るようにした

fix: Zenzaiが無い状態でも動的ユーザ辞書を有効化

---

Sources/KanaKanjiConverterModule/Converter/EmailAddress.swift
Tests/KanaKanjiConverterModuleTests/ConverterTests/EmailAddressConversionTests.swift

Fixes #75
Enhance the email address conversion feature to filter suggestions based on partial domain inputs.
* Update `toEmailAddressCandidates` function in `Sources/KanaKanjiConverterModule/Converter/EmailAddress.swift` to filter suggestions based on the characters before '@'.
* Add logic to check if the input ends with '@' and filter the suggestions based on the characters before '@'.
* Generate suggestions for email domains that match the partial domain input.
* Add tests in `Tests/KanaKanjiConverterModuleTests/ConverterTests/EmailAddressConversionTests.swift` to verify the new filtering functionality for partial domain inputs like '@g' and '@y'.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/ensan-hcl/AzooKeyKanaKanjiConverter/pull/1 …

feat: Enhance email address conversion feature

---

Sources/KanaKanjiConverterModule/Zenz/Zenz.swift

(https://github.com/azooKey/AzooKeyKanaKanjiConverter/pull/122) を削除
Swiftのアップデートで挙動が修正されたため

fix: Windows用のワークアラウンドを削除

---

Sources/CliTool/Subcommands/NGramCommands/TrainCommand.swift
Sources/EfficientNGram/Trainer.swift

ngramの学習のresume処理を実装した。外部から扱う場合、`resumeFilePattern`に学習済みLMのパターンを渡すだけでよい。
```swift
public func trainNGramFromFile(
filePath: String,
n: Int,
baseFilePattern: String,
outputDir: String? = nil,
resumeFilePattern: String? = nil
)
```

feat: ngramの学習のresume処理を実装

---

Sources/KanaKanjiConverterModule/Zenz/ZenzContext.swift

プロンプトの前処理が一貫していなかったため、半角スペースが文脈に入ると変換が不安定になっていた。例えば以下のケースでは「頭痛やく」となってしまっている。
これを修正した。

fix: 前方文脈に半角スペースが入ると変換が不安定になっていた問題を修正

---

Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift
Sources/KanaKanjiConverterModule/Converter/TimeExpression.swift
Tests/KanaKanjiConverterModuleTests/ConverterTests/TimeExpressionTests.swift

Fixes #170
Add functionality to convert 3-digit and 4-digit numbers into time expressions in the format 'HH:MM'.
* Add `convertToTimeExpression` function in `Sources/KanaKanjiConverterModule/Converter/TimeExpression.swift` to handle the conversion.
* Modify `Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift` to include the new function and call it within `getWiseCandidate`.
* Add tests in `Tests/KanaKanjiConverterModuleTests/ConverterTests/TimeExpressionTests.swift` to ensure the new function works correctly.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/azooKey/AzooKeyKanaKanjiConverter/pull/171?shareId=fcdc7916-ae62-4d81-a066-0085f5ef5e97).

feat: Add time expression conversion function

---

Package.swift

"from: 0.8.0"のような指定のためにはバージョニングが必須だったため

feat: use versioning for dependencies

---

Sources/CliTool/Subcommands/DictCommands/BuildCommand.swift
Sources/CliTool/Subcommands/DictCommands/DictCommand.swift
install_cli.sh

Resolve #53 
azooKey_dictionary_builder (https://github.com/azooKey/azooKey_dictionary_builder) はazooKeyの辞書生成パイプラインの出力をazooKey_dictionary_storage形式に変換するためのスクリプトであり、もともとancoよりも先にCLIツールとして公開していた。しかし現状azooKeyに関連する操作はAzooKeyKanaKanjiConverterのCLIツールであるancoに追加するのが通例であり、その点でazooKey_dictionary_builderのみ分離されているのは微妙に使いづらかった。
このPRでは単純にazooKey_dictionary_builderの実装をCLIツールに統合し、辞書の動作確認を行なった。LOUDSBuilderなどはすでにKanaKanjiConverterModuleの側にも実装があるので、今後テストなどを適切に記述しつつ、統合していきたい。

feat: azooKey_dictionary_builderの機能をCliToolに統合

---

Sources/KanaKanjiConverterModule/Converter/CommaSeparatedNumber.swift
Sources/KanaKanjiConverterModule/Converter/ConvertRequestOptions.swift
Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift
Sources/KanaKanjiConverterModule/Converter/SpecialCandidateProvider.swift
Tests/KanaKanjiConverterModuleTests/ConverterTests/CommaSeparatedNumberTests.swift

resolve: https://github.com/azooKey/azooKey/issues/484
- add new `commaSeparatedNumberCandidates` converter
- register `CommaSeparatedNumberSpecialCandidateProvider`
- include the provider in defaults and request options
- test comma separated number conversions
- `swift test --disable-sandbox`

feat: コンマ付き数字の変換候補を追加

---

Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift
Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverterSession.swift
Sources/KanaKanjiConverterModule/LatticeNode.swift
Sources/KanaKanjiConverterModule/RegisteredNodeProtocol.swift
Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ConverterTests/ConverterTests.swift

- manage previous input and node cache in `KanaKanjiConverterSession`
- update `convertToLattice` to take previous input and nodes
- propagate state in session's candidate requests
- switch some converter tests to use sessions
- mark lattice node types as `Sendable` and fix missing session creation
- `swift test -l`

Move lattice state to session

---

Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift
Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverterSession.swift
Sources/KanaKanjiConverterModule/PostCompositionPredictionCandidate.swift

- add per-session caches and zenz state management
- move stop/reset logic and conversion internals into the session actor
- expose wrappers on the converter for backward compatibility
- mark prediction candidate type as `Sendable`
- `swift test`

Refactor session state handling

---

Docs/converter_api.md
Tests/KanaKanjiConverterModuleTests/KanaKanjiConverterSessionTests.swift

- add new asynchronous session tests
- ensure sessions don't interfere with each other
- document `startSession` and `requestCandidatesAsync` usage
- `swift test --filter KanaKanjiConverterSessionTests/testSessionRequestCandidates`
- `swift test --filter KanaKanjiConverterSessionTests/testMultipleSessionsIndependently`
- `swift test`

Add session tests and docs

---

Docs/converter_api.md
Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift
Sources/KanaKanjiConverterModule/DicdataStore/LockedDicdataStore.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/Kana2Kanji.swift
Tests/KanaKanjiConverterModuleTests/KanaKanjiConverterSessionTests.swift

- wrap `DicdataStore` in new `LockedDicdataStore` that synchronizes access
- update converter to use the locked store
- document that sessions share a single converter protected by a lock
- add parallel session test
- note NSLock usage for older platforms
- `swift test -c release`

Add thread-safe DicdataStore wrapper

---

Sources/CliTool/Subcommands/SessionCommand.swift
Sources/KanaKanjiConverterModule/ComposingText.swift
Sources/KanaKanjiConverterModule/DicdataStore/DicdataStore.swift
Sources/KanaKanjiConverterModule/DicdataStore/TypoCorrection.swift
Sources/KanaKanjiConverterModule/Roman2Kana.swift

This pull request introduces several enhancements and fixes across multiple files in the Kana-Kanji conversion module and CLI tool. The most notable changes include adding a new flag to control English candidate mixing, improving debug logging consistency, and refining typo correction logic. Additionally, there are adjustments to the Roman-to-Kana conversion logic to ensure accurate transformations.
* Added a new flag `mixEnglishCandidate` to enable or disable mixing English candidates during Roman-to-Kana input. This flag is wired into the `SessionCommand` logic to dynamically control candidate behavior. [[1]](diffhunk://#diff-cec6a8468aedce2b7fcdfdb9e329f983dd4fec3204525f4f01576c3642a69c5bR16-R17) [[2]](diffhunk://#diff-cec6a8468aedce2b7fcdfdb9e329f983dd4fec3204525f4f01576c3642a69c5bL293 …

fix: getWiseData関連の実装を修正し、bya→ビャなどの変換を適切に表示

---

Package.swift
Sources/CliTool/Anco.swift
Sources/CliTool/Subcommands/EvaluateCommand.swift
Sources/CliTool/Subcommands/ExperimentalPredict.swift
Sources/CliTool/Subcommands/RunCommand.swift
Sources/CliTool/Subcommands/SessionCommand.swift
Sources/CliTool/Subcommands/ZenzEvaluateCommand.swift
Sources/KanaKanjiConverterModule/ComposingText.swift
Sources/KanaKanjiConverterModule/Converter/CalendarCandidate.swift
Sources/KanaKanjiConverterModule/Converter/CommaSeparatedNumber.swift
Sources/KanaKanjiConverterModule/Converter/ConvertRequestOptions.swift
Sources/KanaKanjiConverterModule/Converter/EmailAddress.swift
Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift
Sources/KanaKanjiConverterModule/Converter/RomanTypographys.swift
Sources/KanaKanjiConverterModule/Converter/Unicode.swift
Sources/KanaKanjiConverterModule/Converter/VersionCandidate.swift
Sources/KanaKanjiConverterModule/DicdataStore/DicdataStore.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/zenzai.swift
Sources/KanaKanjiConverterModule/LOUDS/extension LOUDS.swift
Sources/KanaKanjiConverterModule/Replacer/TextReplacer.swift
Sources/KanaKanjiConverterModule/Roman2Kana.swift
Sources/KanaKanjiConverterModule/TemplateData.swift
Sources/KanaKanjiConverterModule/Zenz/Zenz.swift
Sources/KanaKanjiConverterModuleWithDefaultDictionary/KanaKanjiConverterModuleWithDefaultDictionary.swift
Sources/SwiftUtils/ArrayUtils.swift
Sources/SwiftUtils/CharacterUtils.swift
Sources/SwiftUtils/DataUtils.swift
Sources/SwiftUtils/StringUtils.swift

* MemberImportVisibilityに関する機能フラッグを有効化した
* InternalImportsByDefaultに関する機能フラッグを有効化した
参考
* https://github.com/swiftlang/swift-evolution/blob/main/proposals/0409-access-level-on-imports.md
* https://github.com/swiftlang/swift-evolution/blob/main/proposals/0444-member-import-visibility.md
> [!IMPORTANT]
> このPRは既存のAPIの一部を外部に非公開にし、`mutatingForeach`を`mutatingForEach`にリネームする変更を含むので、この変更をリリースする際には0.9.0系への更新が必要です。

feat(breaking): enable upcoming features for future compatibility

---

Sources/KanaKanjiConverterModule/ConverterAPI/KanaKanjiConverter.swift

KanaKanjiConverterのdicdataStore引数ありのコンストラクタを呼んだとしても、先に必ずKana2Kanjiのインスタンスが引数なしコンストラクタで呼ばれてしまうバグを修正します。
[azoo-key-skkserv](https://github.com/gitusp/azoo-key-skkserv) を改造しているときに、コンストラクタにDicdataStoreを渡しているにも関わらず、charID.childを開こうとしているパスが `azoo-key-skkserv.app/louds/charID.chid` のようにapp直下からのパス (workingDirectory) になっているエラーが一度出ていたことで気付きました。
```
Error: louds/charID.chidが存在しません。このエラーは深刻ですが、テスト時には無視できる場合があります。Description: Error Domain=NSCocoaErrorDomain Code=260 "The file “charID.chid” couldn’t be opened because there is no such file." UserInfo={NSFilePath=/Users/xxx/Library/Developer/Xcode/DerivedData/azoo-key-skkserv-dpmfkepsdukakbaxdxbrvepndgjh/Build/Products/Debug/azoo-key-skkserv.app/louds/charID.chid, NSURL=file:///Users/xxx/Library/Developer/Xcode/DerivedData/azoo-key-skkserv-dpmfkepsdukakba …
```

fix: Kana2Kanjiのインスタンスを引数なしで作成してしまうバグを修正

---

Docs/custom_input_table.md

Fix a typo in example of usage:
n{composition-separator}\tん → s{composition-separator}\tす

docs: Fix typo in custom_input_table.md

---

Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/FullInputProcessingWithPrefixConstraint.swift

* 制約付き探索では候補が制約を満たすかを適宜チェックして枝刈りを行うが、このチェックがかなり重たいという問題があった
* そこで、チェックを高速化した

perf: Zenzai用の制約付き探索の実装を改善

---

Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/FullInputProcessingWithPrefixConstraint.swift
Sources/KanaKanjiConverterModule/ConversionAlgorithms/RegisteredNode.swift

LatticeNodeのgetCandidateなどで顕著に改善した。
* Before
* After

perf: RegisteredNodeにindirect enumを用いることで、testGradualConversionのケースにおいてprocessResultの処理時間を20%改善（全体では170ms程度短縮）

---

Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/FullInputProcessing.swift
Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/FullInputProcessingWithPrefixConstraint.swift
Sources/KanaKanjiConverterModule/ConversionAlgorithms/Zenzai/zenzai.swift

* `kana2kanji_all`と`kana2kanji_all_with_prefix_constraint`に`preprocessedLattice`の概念を導入した。ここには事前処理済みの`Lattice`を指定することができ、これがある場合は通常の辞書引きをスキップする
* これにより、Zenzaiでも辞書引き結果をin-call / cross-callでキャッシュできるようになった。
* これを適用したところ、逐次入力の基本的なケースにおいて処理速度が顕著に改善し、最も一般的なローマ字入力のケースでは25%程度の改善になった。

perf: Zenzaiを利用した逐次入力のケースにおいて、辞書データをキャッシュして使いまわすことにより、ZenzaiTests.testGradualConversion_Roman2Kanaのケースで25%の高速化を達成。

---

Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/FullInputProcessing.swift
Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/FullInputProcessingWithPrefixConstraint.swift
Sources/KanaKanjiConverterModule/ConversionAlgorithms/Core/PredictionProcessing.swift
Sources/KanaKanjiConverterModule/ConversionAlgorithms/Prediction.swift
Sources/KanaKanjiConverterModule/DictionaryManagement/DicdataStore.swift

* クラス間連接コストの計算は探索中頻繁に行われるが、ここが思ったよりも時間を食っていた。
* ccValueの取得においてメモリ上の排他制御が問題になっていたので、行単位アクセスに最適化したAPIを用いて改善した
これにより #249 で取り扱ったKanaKanjiConverterModuleWithDefaultDictionaryTests.ZenzaiTests/testGradualConversion_Roman2Kanaのケースでは10%の改善が得られた。一連の高速化の結果は以下の通り。
* #249 適用前: 10.46s
* #249 適用後: 7.69s
* #250 適用後: 6.71s
* #252 適用後: 5.99s

perf: クラス間連接コストの計算を高速化

---

Sources/KanaKanjiConverterModule/DictionaryManagement/DicdataStore.swift

`CCLatter.get`を配列にすることで呼び出しコストを最小化した。おそらくこれでしばらくは連接コスト計算の負荷を気にしなくてよい。

perf: 連接コスト計算が最適化しきれていなかったので最適化した

---

Sources/KanaKanjiConverterModule/DictionaryManagement/DataStructure/DictionaryBuilder.swift
Sources/KanaKanjiConverterModule/DictionaryManagement/DicdataStore.swift
Sources/KanaKanjiConverterModule/DictionaryManagement/LearningMemory.swift
Tests/KanaKanjiConverterModuleTests/DictionaryBuilderTests.swift

fix #259 
辞書データのファイル名に関する大きなbreaking changeであることに留意してください。

feat: 辞書データのファイル名でNON-ASCII文字をエスケープ

---

Sources/CliTool/Subcommands/EvaluateCommand.swift
Sources/KanaKanjiConverterModule/ConverterAPI/KanaKanjiConverter.swift

`anco evaluate`で適切な並びで候補が得られない不具合を修正

fix: evaluate commandの動作を修正
