README.md
Sources/KanaKanjiConverterModule/Converter/ConvertRequestOptions.swift

Add more documents

---

Sources/KanaKanjiConverterModule/CIDData.swift
Sources/KanaKanjiConverterModule/Candidate.swift
Sources/KanaKanjiConverterModule/ComposingText.swift
Sources/KanaKanjiConverterModule/Converter/ConvertRequestOptions.swift
Sources/KanaKanjiConverterModule/DicdataStore/DicdataElement.swift
Sources/KanaKanjiConverterModule/MIDData.swift
Sources/KanaKanjiConverterModule/Replacer/TextReplacer.swift
Sources/KanaKanjiConverterModule/States.swift
Sources/KanaKanjiConverterModule/TemplateData.swift
Sources/SwiftUtils/AppVersion.swift

Add `Sendable` Conformances to possible types.

Add Sendable Conformances

---

Docs/composing_text.md
README.md

[Docs] ComposingTextのドキュメントを追加

---

Sources/KanaKanjiConverterModule/DicdataStore/DicdataElement.swift
Sources/KanaKanjiConverterModule/DicdataStore/DicdataStore.swift

Fix https://github.com/ensan-hcl/azooKey/issues/23

[Bug] TemporalLearningManager由来のデータにpenaltyが適用されない問題を修正

---

Sources/KanaKanjiConverterModule/CIDData.swift
Sources/KanaKanjiConverterModule/MIDData.swift

[Feature] Add more mid and cid data

---

Sources/KanaKanjiConverterModule/LOUDS/LOUDS.swift

[Performance] LOUDSのlookupを高速化

---

.github/dependabot.yml

以下の実装を真似してAZKKCでも利用
https://github.com/ensan-hcl/azooKey/blob/develop/.github/dependabot.yml

[Tools] DependaBotを追加

---

Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/InputGraph/ComposingTextV2.swift
Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ExperimentalTests/InputGraph/InputGraphComponents.swift

* `append`と`removeLast`のみを一旦実装。大半のユースケースはこの2つがあれば問題ない。

[Experimental] ComposingTextV2を実装

---

Sources/KanaKanjiConverterModule/Zenz/ZenzContext.swift

[Fix] Zenzaiのtokenize処理において不必要に指定していたlowerを削除

---

Sources/CliTool/Subcommands/SessionCommand.swift
Sources/KanaKanjiConverterModule/DicdataStore/DicdataElement.swift
Sources/KanaKanjiConverterModule/DicdataStore/LearningMemory.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/all_with_prefix_constraint.swift
Sources/KanaKanjiConverterModule/Zenz/ZenzContext.swift

* `isLearned`を一時学習データを管理する`LearningManager`と、制約付き変換において考慮するように実装を変更した
* `anco session`にコマンドを追加し、`:s`で学習データを一時ディレクトリに書き出せるようにした。これまではできなかった
* そのほか細かい改善を入れた

[Fix] 細かい修正を追加

---

Sources/KanaKanjiConverterModule/Zenz/ZenzContext.swift

#108 で学習を有効化したものの、やや効き過ぎており、副作用が目立つ。そこでzenz-v1の出力を確認し、一定の閾値を越えなければ学習を適用しない方式に変更した。

fix: zenz-v1の出力を学習の適用時に考慮するよう変更

---

Sources/CliTool/Subcommands/SessionCommand.swift
Sources/KanaKanjiConverterModule/Converter/ConvertRequestOptions.swift
Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift
Sources/KanaKanjiConverterModule/Kana2Kanji/zenzai.swift
Sources/KanaKanjiConverterModule/Zenz/Zenz.swift
Sources/KanaKanjiConverterModule/Zenz/ZenzContext.swift

今後リリースする予定のzenz-v2モデルでは、文脈による条件づけが可能になった。これに基づいて
* プロフィール
* 左側の文脈
を変換時に考慮させるAPIを追加した

feat: zenz-v2の文脈による条件づけ機能を活かしたAPIを追加

---

Sources/KanaKanjiConverterModule/Zenz/Zenz.swift

WindowsでZenzaiが動かなくなる問題を修正します（[参考](https://x.com/fkunn1326/status/1826954896404582911)）

small fix for zenzai on windows

---

Sources/KanaKanjiConverterModule/Zenz/ZenzContext.swift

fix: プロフィール付き変換で半角コロンを使うように変更、トークナイザの苦手な文字を削除

---

Sources/KanaKanjiConverterModule/Kana2Kanji/zenzai.swift

fix: 濁点の処理修正PRで存在していた実装の漏れを修正

---

Sources/KanaKanjiConverterModule/ComposingText.swift

* xn→ん の変換が n+子音→ん+子音 の挙動で上書きされてしまう問題を修正

fix: xn→ん の変換が n+子音→ん+子音 の挙動で上書きされてしまう問題を修正

---

.github/workflows/swift.yml
.gitignore

ビルドとテストに使用するswiftのバージョンを安定版に変更します

CI: change swift version to stable

---

Package.swift

commit db29ea2de1dcd6567001b13e92ce415235a5b07f
Author: Masato TOYOSHIMA <phoepsilonix@phoepsilonix.love>
Date:   Sat Oct 12 11:33:06 2024 +0900
Added 'objc' to the linker target of CliTool(Linux) #145
pr #145
Linuxにおいて、Link時にObjcのライブラリが見つからないエラーが出るため、swift build,swift testが失敗します。
それを修正するものです。
Ubuntuのclang-15環境では問題がないようです。
Arch系のclang-18の環境でエラーが出ています。
Ubuntuのclang-15だと-lobjcはエラーになるようです。
なおAndroidでも、-lobjcはエラーになるとのことでした。
そもそも、objective-c環境がない方が、Linuxには多いと思います。
Anrdoid以外のLinuxにおいて、ダミーのファイルをclangにコンパイルさせ、-lobjcオプションが有効かどうかを判断させます。この処理を加えることで、clangなどのバージョンに関係なく、判別できるかと思います。
```sh
swift build -Xswiftc -strict-concurrency=complete -Xcxx -xobjective-c++ -v
```
```
error: link command failed with exit code 1 (use -v to see invocation)
AzooKeyKanaKanjiConverter/.build/x86_64-unknown-linux-gnu/relea …
```

Added 'objc' to the linker target of CliTool(Linux)

---

.github/workflows/swift.yml

- Actionsでビルドを行う代わりに、ビルド済みのSwift Bundleを[ここ](https://github.com/finagolfin/swift-android-sdk/tree/main)から取得し、使用するようにします

AndroidでのCIを修正

---

.github/workflows/swift.yml
.gitmodules
Package.swift
Sources/KanaKanjiConverterModule/Replacer/TextReplacer.swift
Sources/KanaKanjiConverterModuleWithDefaultDictionary/KanaKanjiConverterModuleWithDefaultDictionary.swift
Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/DicdataStoreTests/TextReplacerTests.swift

絵文字ストレージを外部に配置し、これをデフォルトで読み込むように変更した。

feat: use azooKey_emoji_dictionary_storage

---

Sources/CliTool/Subcommands/SessionCommand.swift

dumpとreplayの機能を追加し、同様の処理を繰り返しデバッグする場合に効率よく作業できるようにした。
また、コマンド群を改良し、
* 長い名前も利用可能にした
* :ctxコマンドで文脈をセットできるようにした

feat: sessionコマンドにdump/replayの機能を追加

---

Docs/cli.md
install_cli.sh

* ancoのインストールスクリプトを修正し、Zenzaiを使う場合も単体で動作するようにしました。
* ドキュメントを更新しました。

feat: ancoのインストールスクリプトとドキュメントを更新

---

Sources/KanaKanjiConverterModuleWithDefaultDictionary/KanaKanjiConverterModuleWithDefaultDictionary.swift
Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/DicdataStoreTests/TextReplacerTests.swift

feat: use emoji 16.0

---

Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverter.swift
Sources/KanaKanjiConverterModule/Converter/KanaKanjiConverterSession.swift
Tests/KanaKanjiConverterModuleTests/KanaKanjiConverterSessionTests.swift

- create `KanaKanjiConverterSession` actor that wraps `KanaKanjiConverter`
- expose `startSession()` on `KanaKanjiConverter`
- add test verifying session results match direct converter results
- `swift test -l`
- `swift test --skip-build --filter KanaKanjiConverterSessionTests/testSessionMatchesConverter`

Add converter session actor

---

Sources/CliTool/Subcommands/SessionCommand.swift

- hook up `KanaKanjiConverter.startSession()` inside `SessionCommand`
- route conversions and predictions through the session
- `swift test --list-tests`
- `swift test`

Use session for CLI converter

---

Tests/KanaKanjiConverterModuleTests/KanaKanjiConverterSessionTests.swift

- add async `stopComposition` test cases
- update deprecated synchronous tests to async versions
- add concurrency check with same session
- wait for all tasks in concurrency test
- `swift test --skip-build --filter KanaKanjiConverterSessionTests`
- `swift test` *(fails: missing resources)*

Add async stopComposition test

---

Docs/cli.md
Sources/CliTool/Subcommands/SessionCommand.swift
Sources/KanaKanjiConverterModule/DicdataStore/DicdataStore.swift
Sources/KanaKanjiConverterModule/DicdataStore/LearningMemory.swift
Sources/KanaKanjiConverterModule/States.swift
install_cli.sh

* 学習データの読み取り機能を追加
* 軽いバグを見つけたので修正
* ドキュメントを更新
* `./install_cli.sh --debug`を実装

feat: 学習関連のデバッグのためのCLI整備

---

Sources/KanaKanjiConverterModule/DicdataStore/LearningMemory.swift

iOS版azooKeyで時たま学習がリセットされる問題を観測していたが、検討の結果「誤って`options`を変更しないまま`save`を呼ぶと`char2UInt8`が壊れているためデータが破壊される」という可能性が検出された。そこでこのようなリセットを防ぐため、`options`にデフォルト値を設定しないようにした

feat: LearningManagerの`options`にデフォルト値を設定しないようにした

---

Sources/KanaKanjiConverterModule/DicdataStore/DicdataStore.swift

fix: 「ぁ゚」が優先される問題に対処

---

Sources/KanaKanjiConverterModule/Candidate.swift

perf: parse templateが遅かった（testGradualConversionで25ms程度使う）ので、coarse filterを導入した

---

.github/workflows/swift.yml
Package.swift
README.md
Sources/KanaKanjiConverterModule/ConversionAlgorithms/Zenzai/Zenz/ZenzContext.swift
Sources/KanaKanjiConverterModule/ConversionAlgorithms/Zenzai/Zenz/llama-mock.swift
Tests/KanaKanjiConverterModuleWithDefaultDictionaryTests/ConverterTests/ZenzaiTests.swift
install_cli.sh
profile.sh

feat: CPU推論をサポートし、CIでもこれを活用

---

.github/workflows/swift.yml
Package.swift

fix: rename Kana_k_anji to Kana_K_anji

---

Sources/KanaKanjiConverterModule/DictionaryManagement/DataStructure/extension LOUDS.swift

辞書を読み出す操作を高速化し、この部分はボトルネックではなくなった。

perf: 辞書引きの処理を高速化
